version: '3'
services:
  web:
    build: .
    ports:
     - "80:80"
    volumes:
     - ./src:/app
    environment:
      - ENV=local
  db:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
